---
baseurl: "https://tokio.rs"
title: "Tokio - The asynchronous run-time for the Rust programming language."
languageCode: "en-us"
canonifyURLs: "true"
googleAnalytics: "UA-90234741-1"


params:
  tokioDocsURL: "https://docs.rs/tokio/0.1/tokio"
